springdoc:
  api-docs:
    path: /api-docs
endpoints:
  api-files: http://samyofficefiles-env.eba-zh8kupum.us-east-2.elasticbeanstalk.com/api-files/
  api-analisisRiesgo: http://samyappprimary-env.eba-avd5ffkm.us-east-2.elasticbeanstalk.com/api-analisisRiesgo/
aws:
  config:
    region: us-east-2
    access-key: AKIA5Z6LZFXPAWUQ2LFZ
    secret-key: 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
    service-endpoint: dynamodb.us-east-2.amazonaws.com
  bucket:
    name: archivos-samy-v1
spring:
  main:    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
