springdoc:
  api-docs:
    path: /api-docs
aws:
  config:
    region: us-east-2
    access-key: AKIA5Z6LZFXPAWUQ2LFZ
    secret-key: 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
    service-endpoint: dynamodb.us-east-2.amazonaws.com
  bucket:
    name: archivos-samy-v1
spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
