package com.samy.service.app.model;

import java.io.Serializable;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

@AllArgsConstructor
@DynamoDBTable(tableName = "personal")
@Getter
@NoArgsConstructor
@Setter
@ToString
public class Personal implements Serializable {
    
    private static final long serialVersionUID = 6924923432291661859L;

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    @DynamoDBAttribute(attributeName = "id_personal")
    private String idPersonal;

    @DynamoDBAttribute
    private String datos;

    @DynamoDBAttribute
    private String correo;
}
